image:
  repository: ghcr.io/edmundtse/docker-spideroakone
  pullPolicy: IfNotPresent
  tag: v0.1.0-alpha@sha256:9268202474e4f91b1a87ef63c15bad07c1c2abfce90fedb4446bac9a17c747f8

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
