image:
  repository: taisun/random-images
  pullPolicy: Always
  tag: kasm

securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

persistence:
  varrun:
    enabled: true
