{{ include "common.storage.hostPathValidate" .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ template "common.names.name" . }}
  ports:
    - name: admin
      port: {{ .Values.admin_port | int }}
      targetPort: 3000
      nodePort: {{ .Values.admin_port | int }}
    - name: web
      port: {{ .Values.web_port | int }}
      targetPort: {{ .Values.web_port | int }}
      nodePort: {{ .Values.web_port | int }}
